# Place all the behaviors and hooks related to the matching controller here.
# All this logic will automatically be available in application.js.
# You can use CoffeeScript in this file: http://coffeescript.org/
#
# Original JS:
# $(function() {
#   $('.lessons').sortable({
#     update: function(event, ui) {
#       $.ajax({
#         type: 'PUT',
#         url: ui.item.data('update-url'),
#         dataType: 'json',
#         data: { lesson : { row_order_position : ui.item.index() } }
#       });
#     }
#   });
# });
$ ->
  $('.lessons').sortable update: (event, ui) ->
    $.ajax
      type: 'PUT'
      url: ui.item.data('update-url')
      dataType: 'json'
      data: lesson: row_order_position: ui.item.index()
    return
  return
# ---
# generated by js2coffee 2.2.0
